//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CIISA.RetailOnLine.Droid.webServiceSROL_consultation {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VendedorConsultaSoap", Namespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/")]
    public partial class VendedorConsulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback testConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback existeClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaClientePadronNacionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaInventarioDocumento_pruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaInventarioDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback estadoSistemaCerradoPorFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaBitaRecargaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VendedorConsulta() {
            this.Url = "http://mobile.crciisa.com/ws-v27042017-srol-prod/VendedorConsulta.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event testConnectionCompletedEventHandler testConnectionCompleted;
        
        /// <remarks/>
        public event existeClienteCompletedEventHandler existeClienteCompleted;
        
        /// <remarks/>
        public event consultaClientePadronNacionalCompletedEventHandler consultaClientePadronNacionalCompleted;
        
        /// <remarks/>
        public event consultaInventarioDocumento_pruebaCompletedEventHandler consultaInventarioDocumento_pruebaCompleted;
        
        /// <remarks/>
        public event consultaInventarioDocumentoCompletedEventHandler consultaInventarioDocumentoCompleted;
        
        /// <remarks/>
        public event estadoSistemaCerradoPorFechaCompletedEventHandler estadoSistemaCerradoPorFechaCompleted;
        
        /// <remarks/>
        public event consultaBitaRecargaCompletedEventHandler consultaBitaRecargaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/test", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string test(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("test", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync(SystemCIISA psystemCIISA) {
            this.testAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void testAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[] {
                        psystemCIISA}, this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/testConnection", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool testConnection(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("testConnection", new object[] {
                        psystemCIISA});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void testConnectionAsync(SystemCIISA psystemCIISA) {
            this.testConnectionAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void testConnectionAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.testConnectionOperationCompleted == null)) {
                this.testConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestConnectionOperationCompleted);
            }
            this.InvokeAsync("testConnection", new object[] {
                        psystemCIISA}, this.testConnectionOperationCompleted, userState);
        }
        
        private void OntestConnectionOperationCompleted(object arg) {
            if ((this.testConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testConnectionCompleted(this, new testConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/existeCliente", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool existeCliente(SystemCIISA psystemCIISA, string pcedulaCliente) {
            object[] results = this.Invoke("existeCliente", new object[] {
                        psystemCIISA,
                        pcedulaCliente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void existeClienteAsync(SystemCIISA psystemCIISA, string pcedulaCliente) {
            this.existeClienteAsync(psystemCIISA, pcedulaCliente, null);
        }
        
        /// <remarks/>
        public void existeClienteAsync(SystemCIISA psystemCIISA, string pcedulaCliente, object userState) {
            if ((this.existeClienteOperationCompleted == null)) {
                this.existeClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexisteClienteOperationCompleted);
            }
            this.InvokeAsync("existeCliente", new object[] {
                        psystemCIISA,
                        pcedulaCliente}, this.existeClienteOperationCompleted, userState);
        }
        
        private void OnexisteClienteOperationCompleted(object arg) {
            if ((this.existeClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existeClienteCompleted(this, new existeClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/consultaClientePadronNacional", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string consultaClientePadronNacional(SystemCIISA psystemCIISA, string pcedulaCliente) {
            object[] results = this.Invoke("consultaClientePadronNacional", new object[] {
                        psystemCIISA,
                        pcedulaCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaClientePadronNacionalAsync(SystemCIISA psystemCIISA, string pcedulaCliente) {
            this.consultaClientePadronNacionalAsync(psystemCIISA, pcedulaCliente, null);
        }
        
        /// <remarks/>
        public void consultaClientePadronNacionalAsync(SystemCIISA psystemCIISA, string pcedulaCliente, object userState) {
            if ((this.consultaClientePadronNacionalOperationCompleted == null)) {
                this.consultaClientePadronNacionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaClientePadronNacionalOperationCompleted);
            }
            this.InvokeAsync("consultaClientePadronNacional", new object[] {
                        psystemCIISA,
                        pcedulaCliente}, this.consultaClientePadronNacionalOperationCompleted, userState);
        }
        
        private void OnconsultaClientePadronNacionalOperationCompleted(object arg) {
            if ((this.consultaClientePadronNacionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaClientePadronNacionalCompleted(this, new consultaClientePadronNacionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/consultaInventarioDocumento_prueba", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string consultaInventarioDocumento_prueba() {
            object[] results = this.Invoke("consultaInventarioDocumento_prueba", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaInventarioDocumento_pruebaAsync() {
            this.consultaInventarioDocumento_pruebaAsync(null);
        }
        
        /// <remarks/>
        public void consultaInventarioDocumento_pruebaAsync(object userState) {
            if ((this.consultaInventarioDocumento_pruebaOperationCompleted == null)) {
                this.consultaInventarioDocumento_pruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaInventarioDocumento_pruebaOperationCompleted);
            }
            this.InvokeAsync("consultaInventarioDocumento_prueba", new object[0], this.consultaInventarioDocumento_pruebaOperationCompleted, userState);
        }
        
        private void OnconsultaInventarioDocumento_pruebaOperationCompleted(object arg) {
            if ((this.consultaInventarioDocumento_pruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaInventarioDocumento_pruebaCompleted(this, new consultaInventarioDocumento_pruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/consultaInventarioDocumento", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string consultaInventarioDocumento(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("consultaInventarioDocumento", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaInventarioDocumentoAsync(SystemCIISA psystemCIISA) {
            this.consultaInventarioDocumentoAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void consultaInventarioDocumentoAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.consultaInventarioDocumentoOperationCompleted == null)) {
                this.consultaInventarioDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaInventarioDocumentoOperationCompleted);
            }
            this.InvokeAsync("consultaInventarioDocumento", new object[] {
                        psystemCIISA}, this.consultaInventarioDocumentoOperationCompleted, userState);
        }
        
        private void OnconsultaInventarioDocumentoOperationCompleted(object arg) {
            if ((this.consultaInventarioDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaInventarioDocumentoCompleted(this, new consultaInventarioDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/estadoSistemaCerradoPorFecha", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool estadoSistemaCerradoPorFecha(System.Data.DataTable pfechaToma, SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("estadoSistemaCerradoPorFecha", new object[] {
                        pfechaToma,
                        psystemCIISA});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void estadoSistemaCerradoPorFechaAsync(System.Data.DataTable pfechaToma, SystemCIISA psystemCIISA) {
            this.estadoSistemaCerradoPorFechaAsync(pfechaToma, psystemCIISA, null);
        }
        
        /// <remarks/>
        public void estadoSistemaCerradoPorFechaAsync(System.Data.DataTable pfechaToma, SystemCIISA psystemCIISA, object userState) {
            if ((this.estadoSistemaCerradoPorFechaOperationCompleted == null)) {
                this.estadoSistemaCerradoPorFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnestadoSistemaCerradoPorFechaOperationCompleted);
            }
            this.InvokeAsync("estadoSistemaCerradoPorFecha", new object[] {
                        pfechaToma,
                        psystemCIISA}, this.estadoSistemaCerradoPorFechaOperationCompleted, userState);
        }
        
        private void OnestadoSistemaCerradoPorFechaOperationCompleted(object arg) {
            if ((this.estadoSistemaCerradoPorFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.estadoSistemaCerradoPorFechaCompleted(this, new estadoSistemaCerradoPorFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/consultaBitaRecarga", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string consultaBitaRecarga(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("consultaBitaRecarga", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaBitaRecargaAsync(SystemCIISA psystemCIISA) {
            this.consultaBitaRecargaAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void consultaBitaRecargaAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.consultaBitaRecargaOperationCompleted == null)) {
                this.consultaBitaRecargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaBitaRecargaOperationCompleted);
            }
            this.InvokeAsync("consultaBitaRecarga", new object[] {
                        psystemCIISA}, this.consultaBitaRecargaOperationCompleted, userState);
        }
        
        private void OnconsultaBitaRecargaOperationCompleted(object arg) {
            if ((this.consultaBitaRecargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaBitaRecargaCompleted(this, new consultaBitaRecargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/")]
    public partial class SystemCIISA {
        
        private string _codCompanyField;
        
        private string _codAgentField;
        
        private string _codRuteField;
        
        private string _nameField;
        
        private string _initialsField;
        
        private string _versionField;
        
        /// <remarks/>
        public string _codCompany {
            get {
                return this._codCompanyField;
            }
            set {
                this._codCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string _codAgent {
            get {
                return this._codAgentField;
            }
            set {
                this._codAgentField = value;
            }
        }
        
        /// <remarks/>
        public string _codRute {
            get {
                return this._codRuteField;
            }
            set {
                this._codRuteField = value;
            }
        }
        
        /// <remarks/>
        public string _name {
            get {
                return this._nameField;
            }
            set {
                this._nameField = value;
            }
        }
        
        /// <remarks/>
        public string _initials {
            get {
                return this._initialsField;
            }
            set {
                this._initialsField = value;
            }
        }
        
        /// <remarks/>
        public string _version {
            get {
                return this._versionField;
            }
            set {
                this._versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void testConnectionCompletedEventHandler(object sender, testConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void existeClienteCompletedEventHandler(object sender, existeClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existeClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existeClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void consultaClientePadronNacionalCompletedEventHandler(object sender, consultaClientePadronNacionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaClientePadronNacionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaClientePadronNacionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void consultaInventarioDocumento_pruebaCompletedEventHandler(object sender, consultaInventarioDocumento_pruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaInventarioDocumento_pruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaInventarioDocumento_pruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void consultaInventarioDocumentoCompletedEventHandler(object sender, consultaInventarioDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaInventarioDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaInventarioDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void estadoSistemaCerradoPorFechaCompletedEventHandler(object sender, estadoSistemaCerradoPorFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class estadoSistemaCerradoPorFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal estadoSistemaCerradoPorFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void consultaBitaRecargaCompletedEventHandler(object sender, consultaBitaRecargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaBitaRecargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaBitaRecargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591