//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CIISA.RetailOnLine.Droid.webServiceSROL_rute {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VendedorRutaSoap", Namespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/")]
    public partial class VendedorRuta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback testConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback aperturaNocturnaOperationCompleted;
        
        private System.Threading.SendOrPostCallback aperturaDiurnaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarEstadoSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarInventarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearEstadoSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarEstadoSistema_PruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarRutaEInventario_pruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarRutaEInventarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VendedorRuta() {
            this.Url = "http://mobile.crciisa.com/ws-v27042017-srol-prod/VendedorRuta.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event testConnectionCompletedEventHandler testConnectionCompleted;
        
        /// <remarks/>
        public event aperturaNocturnaCompletedEventHandler aperturaNocturnaCompleted;
        
        /// <remarks/>
        public event aperturaDiurnaCompletedEventHandler aperturaDiurnaCompleted;
        
        /// <remarks/>
        public event eliminarEstadoSistemaCompletedEventHandler eliminarEstadoSistemaCompleted;
        
        /// <remarks/>
        public event eliminarInventarioCompletedEventHandler eliminarInventarioCompleted;
        
        /// <remarks/>
        public event crearEstadoSistemaCompletedEventHandler crearEstadoSistemaCompleted;
        
        /// <remarks/>
        public event eliminarEstadoSistema_PruebaCompletedEventHandler eliminarEstadoSistema_PruebaCompleted;
        
        /// <remarks/>
        public event generarRutaEInventario_pruebaCompletedEventHandler generarRutaEInventario_pruebaCompleted;
        
        /// <remarks/>
        public event generarRutaEInventarioCompletedEventHandler generarRutaEInventarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/test", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string test(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("test", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync(SystemCIISA psystemCIISA) {
            this.testAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void testAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[] {
                        psystemCIISA}, this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/testConnection", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool testConnection(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("testConnection", new object[] {
                        psystemCIISA});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void testConnectionAsync(SystemCIISA psystemCIISA) {
            this.testConnectionAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void testConnectionAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.testConnectionOperationCompleted == null)) {
                this.testConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestConnectionOperationCompleted);
            }
            this.InvokeAsync("testConnection", new object[] {
                        psystemCIISA}, this.testConnectionOperationCompleted, userState);
        }
        
        private void OntestConnectionOperationCompleted(object arg) {
            if ((this.testConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testConnectionCompleted(this, new testConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/aperturaNocturna", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string aperturaNocturna(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("aperturaNocturna", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aperturaNocturnaAsync(SystemCIISA psystemCIISA) {
            this.aperturaNocturnaAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void aperturaNocturnaAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.aperturaNocturnaOperationCompleted == null)) {
                this.aperturaNocturnaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaperturaNocturnaOperationCompleted);
            }
            this.InvokeAsync("aperturaNocturna", new object[] {
                        psystemCIISA}, this.aperturaNocturnaOperationCompleted, userState);
        }
        
        private void OnaperturaNocturnaOperationCompleted(object arg) {
            if ((this.aperturaNocturnaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aperturaNocturnaCompleted(this, new aperturaNocturnaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/aperturaDiurna", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string aperturaDiurna(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("aperturaDiurna", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aperturaDiurnaAsync(SystemCIISA psystemCIISA) {
            this.aperturaDiurnaAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void aperturaDiurnaAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.aperturaDiurnaOperationCompleted == null)) {
                this.aperturaDiurnaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaperturaDiurnaOperationCompleted);
            }
            this.InvokeAsync("aperturaDiurna", new object[] {
                        psystemCIISA}, this.aperturaDiurnaOperationCompleted, userState);
        }
        
        private void OnaperturaDiurnaOperationCompleted(object arg) {
            if ((this.aperturaDiurnaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aperturaDiurnaCompleted(this, new aperturaDiurnaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/eliminarEstadoSistema", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eliminarEstadoSistema(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("eliminarEstadoSistema", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarEstadoSistemaAsync(SystemCIISA psystemCIISA) {
            this.eliminarEstadoSistemaAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void eliminarEstadoSistemaAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.eliminarEstadoSistemaOperationCompleted == null)) {
                this.eliminarEstadoSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarEstadoSistemaOperationCompleted);
            }
            this.InvokeAsync("eliminarEstadoSistema", new object[] {
                        psystemCIISA}, this.eliminarEstadoSistemaOperationCompleted, userState);
        }
        
        private void OneliminarEstadoSistemaOperationCompleted(object arg) {
            if ((this.eliminarEstadoSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarEstadoSistemaCompleted(this, new eliminarEstadoSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/eliminarInventario", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eliminarInventario(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("eliminarInventario", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarInventarioAsync(SystemCIISA psystemCIISA) {
            this.eliminarInventarioAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void eliminarInventarioAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.eliminarInventarioOperationCompleted == null)) {
                this.eliminarInventarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarInventarioOperationCompleted);
            }
            this.InvokeAsync("eliminarInventario", new object[] {
                        psystemCIISA}, this.eliminarInventarioOperationCompleted, userState);
        }
        
        private void OneliminarInventarioOperationCompleted(object arg) {
            if ((this.eliminarInventarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarInventarioCompleted(this, new eliminarInventarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/crearEstadoSistema", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string crearEstadoSistema(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("crearEstadoSistema", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void crearEstadoSistemaAsync(SystemCIISA psystemCIISA) {
            this.crearEstadoSistemaAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void crearEstadoSistemaAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.crearEstadoSistemaOperationCompleted == null)) {
                this.crearEstadoSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearEstadoSistemaOperationCompleted);
            }
            this.InvokeAsync("crearEstadoSistema", new object[] {
                        psystemCIISA}, this.crearEstadoSistemaOperationCompleted, userState);
        }
        
        private void OncrearEstadoSistemaOperationCompleted(object arg) {
            if ((this.crearEstadoSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearEstadoSistemaCompleted(this, new crearEstadoSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/eliminarEstadoSistema_Prueba", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eliminarEstadoSistema_Prueba() {
            object[] results = this.Invoke("eliminarEstadoSistema_Prueba", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarEstadoSistema_PruebaAsync() {
            this.eliminarEstadoSistema_PruebaAsync(null);
        }
        
        /// <remarks/>
        public void eliminarEstadoSistema_PruebaAsync(object userState) {
            if ((this.eliminarEstadoSistema_PruebaOperationCompleted == null)) {
                this.eliminarEstadoSistema_PruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarEstadoSistema_PruebaOperationCompleted);
            }
            this.InvokeAsync("eliminarEstadoSistema_Prueba", new object[0], this.eliminarEstadoSistema_PruebaOperationCompleted, userState);
        }
        
        private void OneliminarEstadoSistema_PruebaOperationCompleted(object arg) {
            if ((this.eliminarEstadoSistema_PruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarEstadoSistema_PruebaCompleted(this, new eliminarEstadoSistema_PruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/generarRutaEInventario_prueba", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string generarRutaEInventario_prueba() {
            object[] results = this.Invoke("generarRutaEInventario_prueba", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generarRutaEInventario_pruebaAsync() {
            this.generarRutaEInventario_pruebaAsync(null);
        }
        
        /// <remarks/>
        public void generarRutaEInventario_pruebaAsync(object userState) {
            if ((this.generarRutaEInventario_pruebaOperationCompleted == null)) {
                this.generarRutaEInventario_pruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarRutaEInventario_pruebaOperationCompleted);
            }
            this.InvokeAsync("generarRutaEInventario_prueba", new object[0], this.generarRutaEInventario_pruebaOperationCompleted, userState);
        }
        
        private void OngenerarRutaEInventario_pruebaOperationCompleted(object arg) {
            if ((this.generarRutaEInventario_pruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarRutaEInventario_pruebaCompleted(this, new generarRutaEInventario_pruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/generarRutaEInventario", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string generarRutaEInventario(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("generarRutaEInventario", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generarRutaEInventarioAsync(SystemCIISA psystemCIISA) {
            this.generarRutaEInventarioAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void generarRutaEInventarioAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.generarRutaEInventarioOperationCompleted == null)) {
                this.generarRutaEInventarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarRutaEInventarioOperationCompleted);
            }
            this.InvokeAsync("generarRutaEInventario", new object[] {
                        psystemCIISA}, this.generarRutaEInventarioOperationCompleted, userState);
        }
        
        private void OngenerarRutaEInventarioOperationCompleted(object arg) {
            if ((this.generarRutaEInventarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarRutaEInventarioCompleted(this, new generarRutaEInventarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/")]
    public partial class SystemCIISA {
        
        private string _codCompanyField;
        
        private string _codAgentField;
        
        private string _codRuteField;
        
        private string _nameField;
        
        private string _initialsField;
        
        private string _versionField;
        
        /// <remarks/>
        public string _codCompany {
            get {
                return this._codCompanyField;
            }
            set {
                this._codCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string _codAgent {
            get {
                return this._codAgentField;
            }
            set {
                this._codAgentField = value;
            }
        }
        
        /// <remarks/>
        public string _codRute {
            get {
                return this._codRuteField;
            }
            set {
                this._codRuteField = value;
            }
        }
        
        /// <remarks/>
        public string _name {
            get {
                return this._nameField;
            }
            set {
                this._nameField = value;
            }
        }
        
        /// <remarks/>
        public string _initials {
            get {
                return this._initialsField;
            }
            set {
                this._initialsField = value;
            }
        }
        
        /// <remarks/>
        public string _version {
            get {
                return this._versionField;
            }
            set {
                this._versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void testConnectionCompletedEventHandler(object sender, testConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void aperturaNocturnaCompletedEventHandler(object sender, aperturaNocturnaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aperturaNocturnaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aperturaNocturnaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void aperturaDiurnaCompletedEventHandler(object sender, aperturaDiurnaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aperturaDiurnaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aperturaDiurnaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarEstadoSistemaCompletedEventHandler(object sender, eliminarEstadoSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarEstadoSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarEstadoSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarInventarioCompletedEventHandler(object sender, eliminarInventarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarInventarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarInventarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void crearEstadoSistemaCompletedEventHandler(object sender, crearEstadoSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearEstadoSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearEstadoSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarEstadoSistema_PruebaCompletedEventHandler(object sender, eliminarEstadoSistema_PruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarEstadoSistema_PruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarEstadoSistema_PruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void generarRutaEInventario_pruebaCompletedEventHandler(object sender, generarRutaEInventario_pruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarRutaEInventario_pruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarRutaEInventario_pruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void generarRutaEInventarioCompletedEventHandler(object sender, generarRutaEInventarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarRutaEInventarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarRutaEInventarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591