//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CIISA.RetailOnLine.Droid.webServiceSROL_download {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VendedorDescargaSoap", Namespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/")]
    public partial class VendedorDescarga : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback testConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback descargaCierreMaquinaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VendedorDescarga() {
            this.Url = "http://mobile.crciisa.com/ws-v27042017-srol-prod/VendedorDescarga.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event testConnectionCompletedEventHandler testConnectionCompleted;
        
        /// <remarks/>
        public event descargaCierreMaquinaCompletedEventHandler descargaCierreMaquinaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/test", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string test(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("test", new object[] {
                        psystemCIISA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync(SystemCIISA psystemCIISA) {
            this.testAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void testAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[] {
                        psystemCIISA}, this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/testConnection", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool testConnection(SystemCIISA psystemCIISA) {
            object[] results = this.Invoke("testConnection", new object[] {
                        psystemCIISA});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void testConnectionAsync(SystemCIISA psystemCIISA) {
            this.testConnectionAsync(psystemCIISA, null);
        }
        
        /// <remarks/>
        public void testConnectionAsync(SystemCIISA psystemCIISA, object userState) {
            if ((this.testConnectionOperationCompleted == null)) {
                this.testConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestConnectionOperationCompleted);
            }
            this.InvokeAsync("testConnection", new object[] {
                        psystemCIISA}, this.testConnectionOperationCompleted, userState);
        }
        
        private void OntestConnectionOperationCompleted(object arg) {
            if ((this.testConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testConnectionCompleted(this, new testConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/descargaCierreMaquina", RequestNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", ResponseNamespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string descargaCierreMaquina(SystemCIISA psystemCIISA, bool pestado, System.DateTime pfecha) {
            object[] results = this.Invoke("descargaCierreMaquina", new object[] {
                        psystemCIISA,
                        pestado,
                        pfecha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void descargaCierreMaquinaAsync(SystemCIISA psystemCIISA, bool pestado, System.DateTime pfecha) {
            this.descargaCierreMaquinaAsync(psystemCIISA, pestado, pfecha, null);
        }
        
        /// <remarks/>
        public void descargaCierreMaquinaAsync(SystemCIISA psystemCIISA, bool pestado, System.DateTime pfecha, object userState) {
            if ((this.descargaCierreMaquinaOperationCompleted == null)) {
                this.descargaCierreMaquinaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescargaCierreMaquinaOperationCompleted);
            }
            this.InvokeAsync("descargaCierreMaquina", new object[] {
                        psystemCIISA,
                        pestado,
                        pfecha}, this.descargaCierreMaquinaOperationCompleted, userState);
        }
        
        private void OndescargaCierreMaquinaOperationCompleted(object arg) {
            if ((this.descargaCierreMaquinaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.descargaCierreMaquinaCompleted(this, new descargaCierreMaquinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mobile.crciisa.com/WS-SROL-V3CAT-PROD/")]
    public partial class SystemCIISA {
        
        private string _codCompanyField;
        
        private string _codAgentField;
        
        private string _codRuteField;
        
        private string _nameField;
        
        private string _initialsField;
        
        private string _versionField;
        
        /// <remarks/>
        public string _codCompany {
            get {
                return this._codCompanyField;
            }
            set {
                this._codCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string _codAgent {
            get {
                return this._codAgentField;
            }
            set {
                this._codAgentField = value;
            }
        }
        
        /// <remarks/>
        public string _codRute {
            get {
                return this._codRuteField;
            }
            set {
                this._codRuteField = value;
            }
        }
        
        /// <remarks/>
        public string _name {
            get {
                return this._nameField;
            }
            set {
                this._nameField = value;
            }
        }
        
        /// <remarks/>
        public string _initials {
            get {
                return this._initialsField;
            }
            set {
                this._initialsField = value;
            }
        }
        
        /// <remarks/>
        public string _version {
            get {
                return this._versionField;
            }
            set {
                this._versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void testConnectionCompletedEventHandler(object sender, testConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void descargaCierreMaquinaCompletedEventHandler(object sender, descargaCierreMaquinaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class descargaCierreMaquinaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal descargaCierreMaquinaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591