CREATE TABLE [TIPOVIATICO](
	[NO_CIA]			[NVARCHAR](2) NOT NULL,
	[CODIGO]			[NVARCHAR](2) NOT NULL,
	[DESCRIPCION]		[NVARCHAR](40) NULL,
	[MONTO_MAXIMO]		[DECIMAL](17,2) NULL,
	[CTA_GASTOS]		[NVARCHAR](15) NULL,
	[FORMULARIO_DOC]	[NVARCHAR](10) NULL,
	[CODIGO_REC]		[NVARCHAR](2) NULL,
	[IND_GENERAL]		[NVARCHAR](1) NULL,
	[IND_TR]			[NVARCHAR](1) NULL,
CONSTRAINT [PK_TIPOVIATICO] PRIMARY KEY([NO_CIA], [CODIGO])
)