CREATE TABLE [PRODUCTO](
	[CODPRODUCTO]		[NVARCHAR](30) NOT NULL,
	[DESCPRODUCTO]		[NVARCHAR](100) NULL,
	[CODCLASIFICACION]	[NVARCHAR](50) NOT NULL,
	[PEDIRPAQUETERIA]	[BIT] NOT NULL,
	[EXENTO]			[BIT] NOT NULL,
	[UNIDAD]			[NVARCHAR](3) NULL,
	[ES_VISCERA]		[NVARCHAR](1) NULL DEFAULT('N'),
	[CAT]				[NVARCHAR](4) NULL,
	[SUBCAT]			[NVARCHAR](4) NULL,
	[PORCENTAJE_IVA]	[INT] NULL,
	[CLAVE_IVA]			[NVARCHAR](2) NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY([CODPRODUCTO])
)