CREATE TABLE [ENCABEZADOTRAMITEBK](
	[NO_CIA]				[NVARCHAR](2) NOT NULL,
	[NO_TRANSA]				[NVARCHAR](16) NOT NULL,
	[NO_CLIENTE]			[NVARCHAR](6) NOT NULL,
	[NO_ESTABLECIMIENTO]	[INT] NULL,
	[NO_AGENTE]				[NVARCHAR](6) NULL,
	--[FECHA_CREA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADOTRAMITEBK_FECHA_CREA] DEFAULT GETDATE(),
	[FECHA_CREA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADOTRAMITEBK_FECHA_CREA] DEFAULT (DATETIME('NOW','LOCALTIME')),
	[MONTO]					[DECIMAL](17, 2) NULL,
	[ENVIADO]				[NVARCHAR](1) NULL,
	--[ANULADO]				[NVARCHAR](1) NULL,	
	[FECHA_TOMA]			[DATETIME] NULL,
	[LATITUD]				[DECIMAL](20, 10) NULL,
	[LONGITUD]				[DECIMAL](20, 10) NULL,
 CONSTRAINT [PK_ENCABEZADOTRAMITEBK] PRIMARY KEY([NO_CIA], [NO_TRANSA], [NO_CLIENTE])
)