--CREATE TABLE [DESCUENTOS](
--	[CONSECUTIVO]	[INT] IDENTITY(1,1) NOT NULL,
--	[CODCIA]		[NVARCHAR](2) NOT NULL,
--	[CODCLIENTE]	[NVARCHAR](6) NULL,
--	[CODPRODUCTO]	[NVARCHAR](30) NULL,
--	--[FAMILIAPRODUCTO] [NVARCHAR](50) NULL,
--	[PORCDESCUENTO] [DECIMAL](4, 2) NOT NULL,
--	[CANTIDAD]		[INT] NOT NULL,
--	[FECHA_INICIA]	[DATETIME] NULL,
--	[FECHA_VENCE]	[DATETIME] NULL,
-- CONSTRAINT [PK_DESCUENTOS] PRIMARY KEY([CONSECUTIVO])
--)

CREATE TABLE [DESCUENTOS](
	[CONSECUTIVO]	INTEGER PRIMARY KEY NOT NULL,
	[CODCIA]		[NVARCHAR](2) NOT NULL,
	[CODCLIENTE]	[NVARCHAR](6) NULL,
	[CODPRODUCTO]	[NVARCHAR](30) NULL,
	--[FAMILIAPRODUCTO] [NVARCHAR](50) NULL,
	[PORCENTAJE]	 [DECIMAL](4, 2) NOT NULL,
	[CANTIDAD]		[INT] NOT NULL,
	[FECHA_INICIA]	[DATETIME] NULL,
	[FECHA_VENCE]	[DATETIME] NULL,
	[TIPO_DESC]		[NVARCHAR](1) NOT NULL DEFAULT('P')
 --CONSTRAINT [PK_DESCUENTOS] PRIMARY KEY([CONSECUTIVO])
)