CREATE TABLE [COMPANNIA](
	[CODCIA]		[NVARCHAR](2) NOT NULL,
	[DESCRIPCION]	[NVARCHAR](50) NOT NULL,
	[RAZONSOCIAL]	[NVARCHAR](50) NOT NULL,
	[CEDJURIDICA]	[NVARCHAR](50) NOT NULL,
 CONSTRAINT [PK_COMPANNIA] PRIMARY KEY([CODCIA])
)