CREATE TABLE [DETALLETRAMITE](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_TRANSA]		[NVARCHAR](16) NOT NULL,
	[NO_LINEA]		[INT] NOT NULL,
	[NO_FACTURA]	[NVARCHAR](12) NULL,
	[MONTO]			[DECIMAL](17, 2) NULL,
	--[FECHA_CREA]	[DATETIME] NULL CONSTRAINT [DF_DETALLETRAMITE_FECHA_CREA] DEFAULT GETDATE(),
	[FECHA_CREA]	[DATETIME] NULL CONSTRAINT [DF_DETALLETRAMITE_FECHA_CREA] DEFAULT (DATETIME('NOW','LOCALTIME')),
	[ENVIADO]		[NVARCHAR](1) NULL,
 CONSTRAINT [PK_DETALLETRAMITE] PRIMARY KEY([NO_CIA], [NO_TRANSA], [NO_LINEA])
)