CREATE TABLE [ENCABEZADOANULACIONBK](
	[NO_CIA]				[NVARCHAR](2) NOT NULL,
	[NO_TRANSA]				[NVARCHAR](12) NOT NULL,
	[NO_CLIENTE]			[NVARCHAR](6) NULL,
	[NO_ESTABLECIMIENTO]	[INT] NULL,
	[NO_AGENTE]				[NVARCHAR](10) NULL,
	[TIPO_DOC]				[NVARCHAR](2) NOT NULL,
	--[FECHA_CREA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADODOCUMENTO_FECHACREACION] DEFAULT GETDATE(),
	[FECHA_CREA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADODOCUMENTO_FECHACREACION] DEFAULT (DATETIME('NOW','LOCALTIME')),
	[FECHA_ENTREGA]			[DATETIME] NULL,
	[TOTAL]					[DECIMAL](17, 2) NULL,
	[TOTAL_IMP]				[DECIMAL](17, 2) NULL,
	[ENVIADO]				[NVARCHAR](1) NULL,
	[FECHA_TOMA]			[DATETIME] NULL,
	[LATITUD]				[DECIMAL](20, 10) NULL,
	[LONGITUD]				[DECIMAL](20, 10) NULL,
 CONSTRAINT [PK_ENCABEZADOANULACIONBK] PRIMARY KEY([NO_CIA], [NO_TRANSA], [TIPO_DOC])
)