CREATE TABLE [TIPOIDENTIFICACION](
	[CODIGO]		[NVARCHAR](1) NOT NULL,
	[DESCRIPCION]	[NVARCHAR](50) NOT NULL,
	[ETIQUETA]		[NVARCHAR](15) NULL,
	[FORMATO]		[NVARCHAR](20) NULL,
	[DIGITO_VERIF]	[INT] NULL,
CONSTRAINT [PK_TIPOIDENTIFICACION] PRIMARY KEY([CODIGO], [DESCRIPCION])
)