CREATE TABLE [CLASIFICACIONCLIENTE](
	[NO_CIA]	[NVARCHAR](2) NOT NULL,
	[CODIGO]	[NVARCHAR](2) NOT NULL,
	[NOMBRE]	[NVARCHAR](60) NOT NULL,
 CONSTRAINT [PK_CLASIFICACIONCLIENTE] PRIMARY KEY([NO_CIA], [CODIGO])
)