CREATE TABLE [LINEA_DOCUMENTO](
	[CONSECUTIVO]		[INT] IDENTITY(1,1) NOT NULL,
	[CODCIA]			[NVARCHAR](2) NULL,
	[CODAGENTE]			[NVARCHAR](6) NOT NULL,
	[CODTIPODOCUMENTO]	[NVARCHAR](2) NULL,
	[CODDOCUMENTO]		[NVARCHAR](16) NULL,
	[LINEA]				[NVARCHAR](100) NULL,
	[COPIA]				[NVARCHAR](1) NULL,
	[ENVIADO]			[NVARCHAR](1) NULL,
	[IMPRESO]			[NVARCHAR](1) NULL,
 CONSTRAINT [PK_LINEA_DOCUMENTO] PRIMARY KEY([CONSECUTIVO])
)