CREATE TABLE [PRECIOCLIENTE](
	[NO_CIA]			[NVARCHAR](2) NOT NULL,
	[NO_CLIENTE]		[NVARCHAR](6) NOT NULL,
	[ARTICULO]			[NVARCHAR](30) NOT NULL,
	[PRECIO_ESPECIAL]	[DECIMAL](18, 2) NULL,
	[TIPO_MTO]			[NVARCHAR](2) NULL,
CONSTRAINT [PK_PRECIOCLIENTE] PRIMARY KEY([NO_CIA], [NO_CLIENTE], [ARTICULO])
)