CREATE TABLE [DESCUENTOGENERAL](
	[CONSECUTIVO]	INTEGER PRIMARY KEY NOT NULL,
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_CLIENTE]	[NVARCHAR](6) NULL,
	[NO_AGENTE]		[NVARCHAR](10) NULL,
	[PORCENTAJE]	[DECIMAL](4, 2) NOT NULL,
	[CANTIDAD]		[INT] NOT NULL,
	[FECHA_INICIA]	[DATETIME] NULL,
	[FECHA_VENCE]	[DATETIME] NULL,
	[TIPO_AGENTE]	[NVARCHAR](1) NULL,
	[TIPO_PRECIO]	[NVARCHAR] NULL,
	[TIPO_DESC]		[NVARCHAR](1) NOT NULL DEFAULT('P')
)