CREATE TABLE [ESTABLECIMIENTO](
	[CODCLIENTE]			[NVARCHAR](6) NOT NULL,
	[CODESTABLECIMIENTO]	[INT] NOT NULL,
	[DESCESTABLECIMIENTO]	[NVARCHAR](150) NOT NULL,
	[DIRECCION]				[NVARCHAR](500) NOT NULL,
	[CODLOCALIZACION]		[NVARCHAR](6) NULL,
	[DIRECCIONEXACTA]		[NVARCHAR](500) NULL,
 CONSTRAINT [PK_ESTABLECIMIENTO] PRIMARY KEY([CODCLIENTE], [CODESTABLECIMIENTO])
)