CREATE TABLE [DETALLERESESBK](
	[CONSECUTIVO]		INTEGER PRIMARY KEY NOT NULL,
	[NO_CIA]			[NVARCHAR](2) NOT NULL,
	[NUM_PEDIDO]		[NUMBER](10) NOT NULL,
	[NO_CLIENTE]		[NVARCHAR](6) NOT NULL,
	[ARTICULO]			[NVARCHAR](30) NOT NULL,
	[IND_TIPO]			[NVARCHAR](1) NULL,
	[FECHA_MATANZA]		[DATETIME] NOT NULL,
	[LOTE]				[NVARCHAR](10) NULL,
	[NO_ANIMAL]			[NVARCHAR](10) NULL,	
	[TIPO_PORCION]		[NVARCHAR](1) NULL,
	[PESO]				[DECIMAL](18, 2) NULL,
	[COMPROMETIDO]		[NVARCHAR](1) NOT NULL DEFAULT ('S'),
	[VENDIDO]			[NVARCHAR](1) NOT NULL DEFAULT ('N'),
	[ENVIADO]			[NVARCHAR](1) NULL DEFAULT('N'),
	[VASIGNADO]			[NVARCHAR](1) NOT NULL DEFAULT('N')
)