CREATE TABLE [CLAVE](
	[NO_CIA]			[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]			[NVARCHAR](10) NOT NULL,
	[PRINCIPAL]			[INT] NULL,
	[TOMA_FISICA]		[INT] NULL,
	[FALTANTES]			[INT] NULL,
	[SMART_CLIENT]		[INT] NULL,
	[CONSECUTIVO]		[INT] NULL,
	[EMERGENCIA]		[INT] NULL,
 CONSTRAINT [PK_CLAVE] PRIMARY KEY([NO_CIA], [NO_AGENTE])
)