CREATE TABLE [RUTA](
	[CODRUTA]				[NVARCHAR](10) NOT NULL,
	[DESCRUTA]				[NVARCHAR](50) NOT NULL,
	[CONSECUTIVODOCUMENTO]	[INT] NOT NULL,
	[CONSECUTIVORECIBO]		[INT] NOT NULL,
 CONSTRAINT [PK_RUTA] PRIMARY KEY([CODRUTA])
)