CREATE TABLE [AUTORIZADOFIRMAR](
	[NO_CIA]			[NVARCHAR](2) NOT NULL,
	[GRUPO]				[NVARCHAR](2) NOT NULL,
	[CLIENTE]			[NVARCHAR](6) NOT NULL,
	[CEDULA_AUTORIZADO]	[NVARCHAR](15) NOT NULL,
	[NOMBRE_AUTORIZADO] [NVARCHAR](100) NULL,
CONSTRAINT [PK_AUTORIZADOFIRMAR] PRIMARY KEY([NO_CIA], [GRUPO], [CLIENTE], [CEDULA_AUTORIZADO])
)