CREATE TABLE [ENCABEZADOPEDIDO](
	[NO_CIA]				[NVARCHAR](2) NOT NULL,
	[NO_TRANSA]				[NVARCHAR](20) NOT NULL,
	[NO_CLIENTE]			[NVARCHAR](6) NOT NULL,
	[NO_ESTABLECIMIENTO]	[INT] NOT NULL,
	[NO_AGENTE]				[NVARCHAR](10) NULL,
	--[FECHA_CREA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADOPEDIDO_FECHA_CREA] DEFAULT GETDATE(),
	[FECHA_CREA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADOPEDIDO_FECHA_CREA] DEFAULT (DATETIME('NOW','LOCALTIME')),
	--[FECHA_ENTREGA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADOPEDIDO_FECHA_ENTREGA] DEFAULT GETDATE(),
	[FECHA_ENTREGA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADOPEDIDO_FECHA_ENTREGA] DEFAULT (DATETIME('NOW','LOCALTIME')),
	[TOTAL]					[DECIMAL](17, 2) NULL,
	[TOTAL_IMP]				[DECIMAL](17, 2) NULL,
	[IND_AUTOMATICO]		[NVARCHAR](1) NULL,
	[ENVIADO]				[NVARCHAR](1) NULL,
	[APLICADO]				[NVARCHAR](1) NULL,
	[PEDIDO_PLANTA]			[NVARCHAR](1) NULL,
 CONSTRAINT [PK_ENCABEZADOPEDIDO] PRIMARY KEY([NO_CIA], [NO_TRANSA], [NO_CLIENTE], [NO_ESTABLECIMIENTO])
)
