CREATE TABLE [EMBALAJE](
	[NO_CIA]	[NVARCHAR](2) NOT NULL,
	[ARTICULO]	[NVARCHAR](30) NOT NULL,
	[EMBALAJE]	[DECIMAL](17, 2) NOT NULL,
	[ORDEN]		[INT] NULL,
 CONSTRAINT [PK_EMBALAJE] PRIMARY KEY([NO_CIA], [ARTICULO], [EMBALAJE])
)