CREATE TABLE [IMPRESORA](
	[NO_CIA]				[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]				[NVARCHAR](10) NOT NULL,
	[PUERTO]				[NVARCHAR](10) NULL,
 CONSTRAINT [PK_IMPRESORA] PRIMARY KEY([NO_CIA], [NO_AGENTE])
)