CREATE TABLE [SISTEMA](
	[CODCIA]		[NVARCHAR](2) NOT NULL,
	[CODAGENTE]		[NVARCHAR](10) NOT NULL,
	[FECHA]			[DATETIME] NOT NULL,
	[IND_CIERRE]	[NVARCHAR](1) NOT NULL,
 CONSTRAINT [PK_SISTEMA] PRIMARY KEY([CODCIA], [CODAGENTE], [FECHA])
)