CREATE TABLE [SINCRONIZACION](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]		[NVARCHAR](6) NOT NULL,
	--CARGA, DESCARGA, ABORTAR
	[TIPO]			[NVARCHAR](2) NULL,
	[HORA]			[DATETIME] NULL,
	
 CONSTRAINT [PK_SINCRONIZACION] PRIMARY KEY([NO_CIA], [NO_AGENTE])
)