CREATE TABLE [ENCABEZADORAZONESNVBK](
	[NO_CIA]				[NVARCHAR](2) NOT NULL,
	[NO_CLIENTE]			[NVARCHAR](6) NOT NULL,
	[NO_AGENTE]				[NVARCHAR](10) NOT NULL,
	[CODIGO]				[NVARCHAR](4) NOT NULL,
	--[FECHA_RUTA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADORAZONESNVBK_FECHA_RUTA] DEFAULT GETDATE(),
	[FECHA_RUTA]			[DATETIME] NULL CONSTRAINT [DF_ENCABEZADORAZONESNVBK_FECHA_RUTA] DEFAULT (DATETIME('NOW','LOCALTIME')),
 --   [FECHA_CREA_MAQUINA]	[DATETIME] NULL CONSTRAINT [DF_ENCABEZADORAZONESNVBK_FECHA_CREA_MAQUINA] DEFAULT GETDATE(),
	[FECHA_CREA_MAQUINA]	[DATETIME] NULL CONSTRAINT [DF_ENCABEZADORAZONESNVBK_FECHA_CREA_MAQUINA] DEFAULT (DATETIME('NOW','LOCALTIME')),
--	[USUARIO_CREA]			[NVARCHAR](60) NULL,
	[ENVIADO]				[NVARCHAR](1) NULL,
 CONSTRAINT [PK_ENCABEZADORAZONESNVBK] PRIMARY KEY([NO_CIA], [NO_CLIENTE], [CODIGO], [NO_AGENTE])
)