CREATE TABLE [PRECIOPRODUCTO](
	[CODLISTAPRECIO]	[INT] NOT NULL,
	[CODPRODUCTO]		[NVARCHAR](30) NOT NULL,
	[PRECIO]			[DECIMAL](18, 2) NOT NULL,
 CONSTRAINT [PK_PRECIOPRODUCTO] PRIMARY KEY([CODLISTAPRECIO], [CODPRODUCTO], [PRECIO])
)