CREATE TABLE [CLIENTECOBRADOR](
	[NO_CIA]				[NVARCHAR](2) NOT NULL,
	[NO_CLIENTE]			[NVARCHAR](6) NOT NULL,
	[NOMBRE]				[NVARCHAR](40) NULL,
	[NOMBRE_LARGO]			[NVARCHAR](80) NULL,
	[CEDULA]				[NVARCHAR](15) NULL,
	[CONDICIONCHEQUE]		[NVARCHAR](1) NULL,
	[PAIS]					[NVARCHAR](6) NULL,
	[PROVINCIA]				[NVARCHAR](6) NULL,
	[CANTON]				[NVARCHAR](6) NULL,
	[DISTRITO]				[NVARCHAR](2) NULL,
	[DIRECCION]				[NVARCHAR](200) NULL,
	[TELEFONO]				[NVARCHAR](15) NULL,
	[COPIAS_FAC]			[INT] NULL,
 CONSTRAINT [PK_CLIENTECOBRADOR] PRIMARY KEY([NO_CIA], [NO_CLIENTE])
)