CREATE TABLE [INDICADORRUTERO](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]		[NVARCHAR](6) NOT NULL,
	[IND_OV]		[NVARCHAR](1) NULL,
	[IND_FC]		[NVARCHAR](1) NULL,
	[IND_FT]		[NVARCHAR](1) NULL,
	[IND_P]			[NVARCHAR](1) NULL,
	[IND_DV]		[NVARCHAR](1) NULL,
	[IND_RG]		[NVARCHAR](1) NULL,
	[IND_RC]		[NVARCHAR](1) NULL,
	[IND_AN]		[NVARCHAR](1) NULL,
	[IND_NV]		[NVARCHAR](1) NULL,
	[IND_TR]		[NVARCHAR](1) NULL,
	[IND_RJ]		[NVARCHAR](1) NULL,
 CONSTRAINT [PK_INDICADORRUTERO] PRIMARY KEY([NO_CIA], [NO_AGENTE])
)