CREATE TABLE [DETALLEANULACIONBK](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_TRANSA]		[NVARCHAR] (12) NOT NULL,
	[NO_LINEA]		[INT] NOT NULL,
	[NO_ARTI]		[NVARCHAR] (30)NULL,
	[TIPO_DOC]		[NVARCHAR](2) NOT NULL,
	[CANTIDAD]		[DECIMAL] (10,2) NULL,
	[COMENTARIO]	[NVARCHAR] (256) NULL,
	[TOTAL_LIN]		[DECIMAL] (17,2) NULL,
	[TOTAL_IMP_LIN]	[DECIMAL] (17,2) NULL,
	[NO_AGENTE]		[NVARCHAR] (10) NULL,
	[ENVIADO]		[NVARCHAR](1) NULL,
	--[FECHA_CREA]	[DATETIME] NULL CONSTRAINT [DF_DETALLEANULACIONBK_FECHA_CREA] DEFAULT GETDATE(),
	[FECHA_CREA]	[DATETIME] NULL CONSTRAINT [DF_DETALLEANULACIONBK_FECHA_CREA] DEFAULT (DATETIME('NOW','LOCALTIME')),
 CONSTRAINT [PK_DETALLEANULACIONBK] PRIMARY KEY([NO_CIA], [NO_TRANSA], [NO_LINEA], [TIPO_DOC])
)