CREATE TABLE [SUGERIDO](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]		[NVARCHAR](6) NOT NULL,
	[NO_CLIENTE]	[NVARCHAR](6) NOT NULL,
	[CODPRODUCTO]	[NVARCHAR](30) NOT NULL,
	[CANTIDAD]		[DECIMAL](18, 2) NOT NULL,
 CONSTRAINT [PK_SUGERIDO] PRIMARY KEY([NO_CIA], [NO_AGENTE], [NO_CLIENTE], [CODPRODUCTO])
)