CREATE TABLE [CUENTACERRADA](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]		[NVARCHAR](6) NOT NULL,
	[NO_CLIENTE]	[NVARCHAR](6) NOT NULL,
	[NOMBRE]		[NVARCHAR](80) NULL,
	[F_CIERRE]		[DATETIME] NULL,
	[MOTIVO]		[NVARCHAR](80) NULL,
 CONSTRAINT [PK_CUENTA_CERRADA] PRIMARY KEY([NO_CIA], [NO_AGENTE], [NO_CLIENTE])
)