CREATE TABLE [INDICADORANULACION](
	[NO_CIA]				[NVARCHAR](3) NOT NULL,
	[NO_AGENTE]				[NVARCHAR](10) NOT NULL,
	[NO_TRANSA]				[NVARCHAR](20) NOT NULL,
CONSTRAINT [PK_INDICADORANULACION] PRIMARY KEY([NO_AGENTE], [NO_TRANSA]))