CREATE TABLE [INFORMACIONRUTA](
	[NO_CIA]		[NVARCHAR](3) NOT NULL,
	[NO_AGENTE]		[NVARCHAR](10) NOT NULL,
	[NOMBREAGENTE]	[NVARCHAR](70) NULL,
	[TIPO_AGENTE]	[NVARCHAR](1) NULL,
	[ESTADO]		[NVARCHAR](1) NULL,
CONSTRAINT [PK_INFORMACIONRUTA] PRIMARY KEY([NO_CIA], [NO_AGENTE]))