CREATE TABLE [CONFIGURACION](
	[CODCIA]		[NVARCHAR](2) NOT NULL,
	[CODAGENTE]		[NVARCHAR](10) NOT NULL,
	--CONTRASEÑA
	[CONTRASENNA]  [NVARCHAR](10) NULL,	
	
	--CONTRASEÑA LIQUIDACION
	--[CONTRA_LIQUI]  [NVARCHAR](10) NULL,
	--CONTRASENA TOMA FÍSICA - RAFA CANTÓN
	--[CONTRA_TOMA]		[NVARCHAR](10) NULL,
	--CONTRASEÑA RECARGA
	--[CONTRA_RECAR]  [NVARCHAR](10) NULL,
	--CONTRASEÑA ABRIR MÁQUINA
	--[CONTRA_ABRIR]  [NVARCHAR](10) NULL,
 CONSTRAINT [PK_SISTEMA] PRIMARY KEY([CODCIA], [CODAGENTE])
)