CREATE TABLE [AGENTEVENDEDOR](
	[NO_CIA]				[NVARCHAR](3) NOT NULL,
	[NO_AGENTE]				[NVARCHAR](10) NOT NULL,
	[NOM_AGENTE]			[NVARCHAR](70) NOT NULL,
	--[IDCLIENTE]				[NVARCHAR](5) NULL,
	[NO_RUTA]				[NVARCHAR](4) NOT NULL,
	[USUARIO]				[NVARCHAR](25) NULL,
	[CONTRASENNA]			[NVARCHAR](50) NULL,
	[CONSECUTIVO_DOC]		[NVARCHAR](16) NULL,
	[CONSECUTIVO_REC]		[NVARCHAR](16) NULL,
	[CONSECUTIVO_CLI]		[NVARCHAR](16) NULL,
	--
	[CONSECUTIVO_OV]		[NVARCHAR](16) NULL,--orden de venta
	--[CONSECUTIVO_FC]		  [NVARCHAR](16) NULL,--factura contado
	--[CONSECUTIVO_FT]		  [NVARCHAR](16) NULL,--factura credito
	[CONSECUTIVO_P]			[NVARCHAR](16) NULL,--cotizacion
	[CONSECUTIVO_DV]		[NVARCHAR](16) NULL,--devolucion
	[CONSECUTIVO_RG]		[NVARCHAR](16) NULL,--regalia
	[CONSECUTIVO_RC]		[NVARCHAR](16) NULL,--recaudacion
	[CONSECUTIVO_AN]		[NVARCHAR](16) NULL,--anulacion
	--[CONSECUTIVO_RJ]		  [NVARCHAR](16) NULL,--recibo dinero
	[CONSECUTIVO_TR]		[NVARCHAR](16) NULL,--anulacion
	[CONSECUTIVO_PD]		[NVARCHAR](16) NULL,--anulacion
	[TIPO_AGENTE]			[NVARCHAR](1) NULL,
	--[CODCLIENTEGENERICO]	[NVARCHAR](6) NULL,
	[CLIENTE_NUEVO]			[NVARCHAR](6) NULL,
	[TIPO_IMPRESORA]		[NVARCHAR](6) NULL,
	[CODIGO_SECTOR]			[NVARCHAR](3) NULL,
	[NO_EMPLE]				[NVARCHAR](6) NULL,
	[CONSECUTIVO_VT]		[NVARCHAR](12) NULL,
	[CODIGO_CLIENTE]		[NVARCHAR](30) NULL,
CONSTRAINT [PK_AGENTEVENDEDOR] PRIMARY KEY([NO_CIA], [NO_AGENTE]))