CREATE TABLE [FECHASERVIDOR](
	[FECHASERVIDOR] [DATETIME] NOT NULL,
	[ANNO]			[NVARCHAR](4) NOT NULL,
	[MES]			[NVARCHAR](2) NOT NULL,
	[DIA]			[NVARCHAR](2) NOT NULL,
	[HORA]			[NVARCHAR](2) NOT NULL,
	[MINUTOS]		[NVARCHAR](2) NOT NULL,
	[AMPM]			[NVARCHAR](4) NOT NULL,
	[ACTUALIZADA]	[NVARCHAR](6) NULL,
 CONSTRAINT [PK_FECHASERVIDOR] PRIMARY KEY([FECHASERVIDOR])
)