CREATE TABLE [SMS](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[NO_AGENTE]		[NVARCHAR](10) NOT NULL,
	[TIPO_DOC]		[NVARCHAR](2) NOT NULL,
	[COORDENADAS]	[NVARCHAR](50) NULL,
	[SMS]			[NVARCHAR](2) NULL,
	[TELEFONO_1]	[NVARCHAR](10) NULL,
	[TELEFONO_2]	[NVARCHAR](10) NULL,
	[TELEFONO_3]	[NVARCHAR](10) NULL,
 CONSTRAINT [PK_SMS] PRIMARY KEY([NO_CIA], [NO_AGENTE], [TIPO_DOC])
)