CREATE TABLE [BITACORABK](
	[COD_CLIENTE]					[NVARCHAR](50)	NOT NULL,
	[FECHAVISITA]					[DATETIME]		NULL,
	[VOLCOMPRA]						[NVARCHAR](30)	NULL,
	[PORCENTAJECOMPRA]				[DECIMAL](4, 2) NOT NULL,
	[SITUACION]						[NVARCHAR](600)	NULL,
	[QUEJAS]						[NVARCHAR](600)	NULL,
	[OPORTUNIDADES]					[NVARCHAR](600)	NULL,
	[COMPETENCIAS]					[NVARCHAR](600)	NULL,
	[ENVIADO]						[NVARCHAR](1) NULL DEFAULT('N')
)