CREATE TABLE [ESPECIFICACION](
	[NO_CIA]		[NVARCHAR](2) NOT NULL,
	[CODIGO]		[NVARCHAR](4) NOT NULL,
	[DESCRIPCION]	[NVARCHAR](30) NULL,
 CONSTRAINT [PK_ESPECIFICACION] PRIMARY KEY([NO_CIA], [CODIGO])
)