CREATE TABLE [DETALLERECIBO](
		[NO_CIA]		[NVARCHAR](2) NOT NULL,
		[NO_TRANSA]		[NVARCHAR](16) NOT NULL,
		[NO_FACTURA]	[NVARCHAR](12) NOT NULL,
		[MONTO]			[DECIMAL](17,2) NULL,
		[TIPO_DOC]		[NVARCHAR](2) NOT NULL,
		[NO_LINEA]		[INT] NOT NULL,
		--[FECHA_CREA]	[DATETIME] NULL CONSTRAINT [DF_DETALLERECIBO_FECHA_CREA] DEFAULT GETDATE(),
		[FECHA_CREA]	[DATETIME] NULL CONSTRAINT [DF_DETALLERECIBO_FECHA_CREA] DEFAULT (DATETIME('NOW','LOCALTIME')),
		[ENVIADO]		[NVARCHAR](1) NULL,
		[ANULADO]		[NVARCHAR](1) NULL,
		[TIPO_TRANSA]	[NVARCHAR](2) NULL,	
 CONSTRAINT [PK_DETALLERECIBO] PRIMARY KEY([NO_CIA], [NO_TRANSA], [NO_FACTURA], [NO_LINEA])
)