CREATE TABLE [MENSAJEFACTURA](
	[CONSECUTIVO]	INTEGER PRIMARY KEY NOT NULL,
	[NO_CIA]		[NVARCHAR](2) NULL,
	[COMENTARIO]	[NVARCHAR] NULL,
	[COMENTARIO1]	[NVARCHAR] NULL,
	[COMENTARIO2]	[NVARCHAR] NULL,
	[COMENTARIO3]	[NVARCHAR] NULL,
	[COMENTARIO4]	[NVARCHAR] NULL
)