--no_cia, no_cliente, tipo_doc, saldo, no_fisico, fecha_documento
CREATE TABLE [DOCUMENTO](
	[NO_CIA]			[NVARCHAR](2) NOT NULL,
	[NO_CLIENTE]		[NVARCHAR](6) NOT NULL,
	[TIPO_DOC]			[NVARCHAR](2) NOT NULL,
	[SALDO]				[DECIMAL](17,2) NULL,
	[NO_FISICO]			[NVARCHAR](12) NOT NULL,
	[FECHA_DOCUMENTO]	[NVARCHAR](6) NULL,	
 CONSTRAINT [PK_DETALLERECIBO] PRIMARY KEY([NO_CIA], [NO_CLIENTE], [NO_FISICO])
)