CREATE TABLE [DISTRITO](
	[PAIS]			[NVARCHAR](6) NOT NULL,
	[PROVINCIA]		[NVARCHAR](6) NOT NULL,
	[CANTON]		[NVARCHAR](6) NOT NULL,
	[DISTRITO]		[NVARCHAR](6) NOT NULL,
	[DESCRIPCION]	[NVARCHAR](25) NULL,
 CONSTRAINT [PK_CANTON] PRIMARY KEY([PAIS], [PROVINCIA], [CANTON], [DISTRITO])
)