CREATE TABLE [VISITAS](
	[CODCIA]				[NVARCHAR](2) NOT NULL,
	[CODRUTA]				[NVARCHAR](10) NOT NULL,
	[DIA]					[NVARCHAR](1) NOT NULL,
	[CODESTABLECIMIENTO]	[INT] NOT NULL,
	[CODCLIENTE]			[NVARCHAR](6) NOT NULL,
	[ORDEN]					[INT] NULL,
 CONSTRAINT [PK_VISITAS] PRIMARY KEY([CODCIA], [CODRUTA], [DIA], [CODESTABLECIMIENTO], [CODCLIENTE])
)